#!/bin/bash

ARGS="3"

if [ "$#" -ne "$ARGS" ]; then
    echo "Expected number of $ARGS arguments, you gave $#."
    exit -1
fi

remainder="0"

# Addition
if [ "$2" == "+" ]; then
    result=$(($1 + $3))

# Subtraction
elif [ "$2" == "-" ]; then
    result=$(($1 - $3))

# Multiplication
elif  [ "$2" == "x" ]; then
    result=$(($1 * $3))

# Valid Division
elif  [ "$2" == "/" -a "$3" -ne 0 ]; then
    result=$(($1 / $3))
    remainder=$(($1 % $3))

# Not valid Division
elif  [ "$2" == "/" -a "$3" -eq 0 ]; then
    echo "Cannot divide with 0."
    exit -1

# Power of
elif  [ "$2" == "^" ]; then
    result=$(($1 ** $3))

# Modulus
elif  [ "$2" == "%" ]; then
    result=$(($1 % $3))

else
    echo "Invalid operator, supports +, -, x,  /, ^ and % operators."
    exit -3
fi

# Echo given arguments and the result
if [ $remainder -eq 0 ]; then
    echo "$1 $2 $3 = $result"

else
    echo "$1 $2 $3 = $result with a remainder of $remainder"
fi
